[package]
name = "fctrl"
version = "0.1.0"
authors = ["circlesabound <circlesabound@users.noreply.github.com>"]
edition = "2018"
license = "Apache-2.0"
publish = false

[dependencies]
bincode = "1.3"
bytes = "1.0"
chrono = { version = "0.4", features = [ "serde" ] }
derive_more = "0.99"
env_logger = "0.8"
factorio-mod-settings-parser = { git = "https://github.com/circlesabound/factorio-mod-settings-parser", rev = "a9fecd6" }
futures = "0.3"
futures-util = "0.3"
lazy_static = "1.4"
log = "0.4"
nix = "0.20"
rcon = "0.4"
regex = "1.4"
reqwest = { version = "0.11", features = [ "json" ] }
rocksdb = "0.16"
rocket = { git = "https://github.com/SergioBenitez/Rocket", rev = "fe23eaebd1bad066afcc2d2470f3a87aff2f53c4" }
rocket_contrib = { git = "https://github.com/SergioBenitez/Rocket", rev = "fe23eaebd1bad066afcc2d2470f3a87aff2f53c4", default-features = false, features = [ "json", "serve" ]}
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
strum = "0.20"
strum_macros = "0.20"
tar = "0.4"
tokio = { version = "1.5", features = [ "full" ] }
tokio-stream = { version = "0.1", features = [ "sync" ] }
tokio-tungstenite = "0.14"
toml = "0.5"
url = "2"
uuid = { version = "0.8", features = [ "serde", "v4" ] }
xz2 = "0.1"

[dev-dependencies]
serial_test = "0.5"

[[bin]]
name = "agent"
path = "src/agent/main.rs"

[[bin]]
name = "mgmt-server"
path = "src/mgmt-server/main.rs"

[[bin]]
name = "ws-client"
path = "src/ws-client/main.rs"
