[package]
name = "fctrl-agent"
version = "0.1.0"
authors = ["circlesabound <circlesabound@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
env_logger = "0.8"
futures-util = "0.3"
lazy_static = "1.4"
log = "0.4"
logwatcher = "0.1"
rcon = "0.4"
regex = "1.4"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
tokio = { version = "1.2", features = [ "full" ] }
tokio-tungstenite = "*"
toml = "0.5"
