[package]
name = "fctrl"
version = "0.1.0"
authors = ["circlesabound <circlesabound@users.noreply.github.com>"]
edition = "2018"

[dependencies]
bytes = "1.0"
derive_more = "0.99"
env_logger = "0.8"
futures = "0.3"
futures-util = "0.3"
lazy_static = "1.4"
log = "0.4"
logwatcher = "0.1"
nix = "0.20"
rcon = "0.4"
regex = "1.4"
reqwest = "0.11"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
tar = "0.4"
tokio = { version = "1.5", features = [ "full" ] }
tokio-tungstenite = "0.14"
toml = "0.5"
url = "2"
uuid = { version = "0.8", features = [ "serde", "v4" ] }
xz2 = "0.1"

[[bin]]
name = "agent"
path = "src/agent/main.rs"

[[bin]]
name = "mgmt-server"
path = "src/mgmt_server/main.rs"

[[bin]]
name = "ws-client"
path = "src/ws_client/main.rs"
