version: '3.8'
services:
  agent:
    image: ghcr.io/circlesabound/fctrl/agent:latest
    build:
      context: .
      dockerfile: agent.Dockerfile
  mgmt-server:
    image: ghcr.io/circlesabound/fctrl/mgmt-server:latest
    build:
      context: .
      dockerfile: mgmt-server.Dockerfile
