version: '3.8'
services:
  agent:
    image: ghcr.io/circlesabound/fctrl/agent:latest
    volumes:
      - type: bind
        source: ./data
        target: /app/data
    environment:
      - AGENT_WS_PORT
      - FACTORIO_PORT
      - FACTORIO_RCON_PORT
      - RUST_LOG=${LOG_LEVEL}
    ports:
      - '127.0.0.1:${AGENT_WS_PORT}:${AGENT_WS_PORT}/tcp'
      - '${FACTORIO_PORT}:${FACTORIO_PORT}/udp'
      - '${FACTORIO_RCON_PORT}:${FACTORIO_RCON_PORT}/tcp'
    stop_signal: SIGINT
  mgmt-server:
    image: ghcr.io/circlesabound/fctrl/mgmt-server:latest
    volumes:
      - type: bind
        source: ./db
        target: /app/db
    environment:
      - AGENT_ADDR=ws://agent:${AGENT_WS_PORT}
      - AUTH_PROVIDER
      - AUTH_DISCORD_ADMIN_USER_ID
      - DISCORD_INTEGRATION
      - DISCORD_BOT_TOKEN
      - DISCORD_OAUTH2_CLIENT_ID
      - DISCORD_OAUTH2_CLIENT_SECRET
      - MGMT_SERVER_WS_ADDRESS=${MGMT_SERVER_BIND}
      - MGMT_SERVER_WS_PORT
      - ROCKET_ADDRESS=${MGMT_SERVER_BIND}
      - ROCKET_LOG_LEVEL=critical
      - ROCKET_PORT=${MGMT_SERVER_PORT}
      - RUST_LOG=${LOG_LEVEL}
    ports:
      - '${MGMT_SERVER_BIND}:${MGMT_SERVER_PORT}:${MGMT_SERVER_PORT}/tcp'
      - '${MGMT_SERVER_WS_PORT}:${MGMT_SERVER_WS_PORT}/tcp'
    stop_signal: SIGINT
