name: Build and push container images

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: docker-compose build
      run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml build --build-arg GIT_COMMIT_HASH=${{ github.sha }}
      env:
        DOCKER_BUILDKIT: 1
    - name: login to registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u circlesabound --password-stdin
    - name: push agent
      run: docker push ghcr.io/circlesabound/fctrl/agent:latest
    - name: push mgmt-server
      run: docker push ghcr.io/circlesabound/fctrl/mgmt-server:latest
